
//! Autogenerated weights for `pallet_kitties`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2024-09-23, STEPS: `20`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `o290`, CPU: `12th Gen Intel(R) Core(TM) i5-12500H`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/production/solochain-template-node
// benchmark
// pallet
// --chain
// dev
// --execution=wasm
// --pallet
// pallet_kitties
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --output
// pallets/kitties/src/weights.rs
// --template
// .maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_kitties`.
pub trait WeightInfo {
	fn create() -> Weight;
	fn breed() -> Weight;
	fn transfer() -> Weight;
	fn sale() -> Weight;
	fn bid() -> Weight;
}

/// Weights for `pallet_kitties` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Random::RandomMaterial` (r:1 w:0)
	/// Proof: `Random::RandomMaterial` (`max_values`: Some(1), `max_size`: Some(2594), added: 3089, mode: `MaxEncodedLen`)
	/// Storage: `KittiesModule::NextKittyId` (r:1 w:1)
	/// Proof: `KittiesModule::NextKittyId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `KittiesModule::Kitties` (r:0 w:1)
	/// Proof: `KittiesModule::Kitties` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `KittiesModule::KittyOwner` (r:0 w:1)
	/// Proof: `KittiesModule::KittyOwner` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn create() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `45`
		//  Estimated: `4079`
		// Minimum execution time: 20_155_000 picoseconds.
		Weight::from_parts(21_143_000, 4079)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `KittiesModule::Kitties` (r:2 w:1)
	/// Proof: `KittiesModule::Kitties` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `KittiesModule::KittyOwner` (r:2 w:1)
	/// Proof: `KittiesModule::KittyOwner` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Random::RandomMaterial` (r:1 w:0)
	/// Proof: `Random::RandomMaterial` (`max_values`: Some(1), `max_size`: Some(2594), added: 3089, mode: `MaxEncodedLen`)
	/// Storage: `KittiesModule::NextKittyId` (r:1 w:1)
	/// Proof: `KittiesModule::NextKittyId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn breed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `302`
		//  Estimated: `6044`
		// Minimum execution time: 30_539_000 picoseconds.
		Weight::from_parts(32_253_000, 6044)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `KittiesModule::Kitties` (r:1 w:0)
	/// Proof: `KittiesModule::Kitties` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `KittiesModule::KittyOwner` (r:1 w:1)
	/// Proof: `KittiesModule::KittyOwner` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `303`
		//  Estimated: `3593`
		// Minimum execution time: 29_845_000 picoseconds.
		Weight::from_parts(30_566_000, 3593)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `KittiesModule::Kitties` (r:1 w:0)
	/// Proof: `KittiesModule::Kitties` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `KittiesModule::KittyOwner` (r:1 w:0)
	/// Proof: `KittiesModule::KittyOwner` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `KittiesModule::KittyOnSale` (r:1 w:1)
	/// Proof: `KittiesModule::KittyOnSale` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	fn sale() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `200`
		//  Estimated: `3517`
		// Minimum execution time: 12_491_000 picoseconds.
		Weight::from_parts(12_933_000, 3517)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `KittiesModule::Kitties` (r:1 w:0)
	/// Proof: `KittiesModule::Kitties` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `KittiesModule::KittyOwner` (r:1 w:0)
	/// Proof: `KittiesModule::KittyOwner` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `KittiesModule::KittyOnSale` (r:1 w:0)
	/// Proof: `KittiesModule::KittyOnSale` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	/// Storage: `KittiesModule::KittiesBid` (r:1 w:1)
	/// Proof: `KittiesModule::KittiesBid` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn bid() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `364`
		//  Estimated: `3593`
		// Minimum execution time: 27_405_000 picoseconds.
		Weight::from_parts(29_402_000, 3593)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Random::RandomMaterial` (r:1 w:0)
	/// Proof: `Random::RandomMaterial` (`max_values`: Some(1), `max_size`: Some(2594), added: 3089, mode: `MaxEncodedLen`)
	/// Storage: `KittiesModule::NextKittyId` (r:1 w:1)
	/// Proof: `KittiesModule::NextKittyId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `KittiesModule::Kitties` (r:0 w:1)
	/// Proof: `KittiesModule::Kitties` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `KittiesModule::KittyOwner` (r:0 w:1)
	/// Proof: `KittiesModule::KittyOwner` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn create() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `45`
		//  Estimated: `4079`
		// Minimum execution time: 20_155_000 picoseconds.
		Weight::from_parts(21_143_000, 4079)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `KittiesModule::Kitties` (r:2 w:1)
	/// Proof: `KittiesModule::Kitties` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `KittiesModule::KittyOwner` (r:2 w:1)
	/// Proof: `KittiesModule::KittyOwner` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Random::RandomMaterial` (r:1 w:0)
	/// Proof: `Random::RandomMaterial` (`max_values`: Some(1), `max_size`: Some(2594), added: 3089, mode: `MaxEncodedLen`)
	/// Storage: `KittiesModule::NextKittyId` (r:1 w:1)
	/// Proof: `KittiesModule::NextKittyId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn breed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `302`
		//  Estimated: `6044`
		// Minimum execution time: 30_539_000 picoseconds.
		Weight::from_parts(32_253_000, 6044)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `KittiesModule::Kitties` (r:1 w:0)
	/// Proof: `KittiesModule::Kitties` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `KittiesModule::KittyOwner` (r:1 w:1)
	/// Proof: `KittiesModule::KittyOwner` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `303`
		//  Estimated: `3593`
		// Minimum execution time: 29_845_000 picoseconds.
		Weight::from_parts(30_566_000, 3593)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `KittiesModule::Kitties` (r:1 w:0)
	/// Proof: `KittiesModule::Kitties` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `KittiesModule::KittyOwner` (r:1 w:0)
	/// Proof: `KittiesModule::KittyOwner` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `KittiesModule::KittyOnSale` (r:1 w:1)
	/// Proof: `KittiesModule::KittyOnSale` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	fn sale() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `200`
		//  Estimated: `3517`
		// Minimum execution time: 12_491_000 picoseconds.
		Weight::from_parts(12_933_000, 3517)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `KittiesModule::Kitties` (r:1 w:0)
	/// Proof: `KittiesModule::Kitties` (`max_values`: None, `max_size`: Some(36), added: 2511, mode: `MaxEncodedLen`)
	/// Storage: `KittiesModule::KittyOwner` (r:1 w:0)
	/// Proof: `KittiesModule::KittyOwner` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `KittiesModule::KittyOnSale` (r:1 w:0)
	/// Proof: `KittiesModule::KittyOnSale` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	/// Storage: `KittiesModule::KittiesBid` (r:1 w:1)
	/// Proof: `KittiesModule::KittiesBid` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn bid() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `364`
		//  Estimated: `3593`
		// Minimum execution time: 27_405_000 picoseconds.
		Weight::from_parts(29_402_000, 3593)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}