[relaychain]
default_command = "polkadot"
chain = "rococo-local"

[[relaychain.nodes]]
name = "alice"
validator = true
ws_port = 9944

[[relaychain.nodes]]
name = "bob"
validator = true
ws_port = 9955

[[parachains]]
id = 1000

[parachains.collator]
name = "charlie"
ws_port = 9988
command = "parachain-template-node"
args = [
		"-lparachain=debug,xcm::process-message=trace,xcm::execute=trace,xcm::process=trace"
]

[[parachains]]
id = 1001

[parachains.collator]
name = "dave"
ws_port = 9999
command = "parachain-template-node"
args = [
		"-lparachain=debug,xcm::process-message=trace,xcm::execute=trace,xcm::process=trace"
]
